### ISSUE TITLE
Have you heard of WP-CLI?

### ISSUE THREAD

**Issue by danielbachhuber** [weknowinc/wp-console#2]
Hi!

Curious if you've heard of [WP-CLI](http://wp-cli.org/), the official CLI for WordPress?

If you haven't, we'd love to have you contribute your efforts to WP-CLI instead.

**Comment by enzolutions** [comment]
Hi @danielbachhuber 

Of course, we know about [WP-CLI](http://wp-cli.org/) and maybe you hear about [Drupal Console](http://drupalconsole.com).

At [weKnow](http://weknowinc.com) we have been working on a Platform as a Software **PaaS** that require some [WordPress](https://wordpress.org) command line integration.

On the beginning, we tried to use **WP-CLI**, but sooner we notice that our needs of Symfony components and other tools required for our project, were not fully compatible with **WP-CLI**.

For this reason, we started a new CLI implementation for Wordpress, using the knowledge we gain during the development of **Drupal Console** project; In the middle of the process, we decided to release our **WordPress** CLI integration as Open Source.

We have the idea, that this tool could facilitate to Symfony and Drupal users to get involved with **WordPress** easily because they would have something in common since we use Symfony Console and a similar implementation of this component in  **Drupal Console**.

About contribution, we are trying to create the project modularly; On this way in the future, if **WP-CLI** decide to use composer packages, we could split this project into libraries that could be shared on both platforms.

What should we understand when you said **WP-CLI** is the official?

As any other Open Source initiative, **wp-console** don't pretend to be official or replace anything else; Is just a project that we think could be useful for some people and by the way we are trying to solve other needs in areas of code generation, system introspection and continues integration in the **WordPress** universe. 

Under our understanding, the goals and objectives of both projects are different, but similar because both are related to the same project which is **WordPress**

**Comment by danielbachhuber** [comment]
> Of course, we know about WP-CLI

Great!

> maybe you hear about Drupal Console.

Yes, of course.

> On the beginning, we tried to use WP-CLI, but sooner we notice that our needs of Symfony components and other tools required for our project, were not fully compatible with WP-CLI.
> 
> For this reason, we started a new CLI implementation for Wordpress, using the knowledge we gain during the development of Drupal Console project; In the middle of the process, we decided to release our WordPress CLI integration as Open Source.

Makes sense. Seems a shame to duplicate efforts though.

> About contribution, we are trying to create the project modularly; On this way in the future, if WP-CLI decide to use composer packages, we could split this project into libraries that could be shared on both platforms.

We're already headed in that direction, see https://github.com/wp-cli/wp-cli/issues/3728

However, at this point, we have no plans to adopt Symfony console, related https://github.com/wp-cli/wp-cli/issues/3717

> What should we understand when you said WP-CLI is the official?

Just a small point on semantics. WP-CLI is "The command line interface for WordPress". Your project would be better described as "A command line interface for WordPress", "Another command line interface for WordPress" or "A Symfony Console-based command line interface for WordPress"

**Comment by enzolutions** [comment]
Thanks for the update about WP-CLI and your feedback
